version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build Site
          command: echo Hello, world.
      - run:
          name: Deploy Site
          command: sh ./.circleci/deploy_gh_pages.sh dist