version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
        name: Build Site
        command: echo Hello, world.
      - run:
        name: Deploy Site
        commands:
          - ./scripts/deploy-ghpages.sh build dist