version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build Site
          command: echo Hello, world.
      - run:
        branch: master
        commands:
          - ./scripts/deploy-ghpages.sh build dist